# This generates the skeleton for a Rest API definition. Outputs to console

env :
    projectHomeDir : /Users/sandeep/projects/source/CodeGenConfigs/
    codegenProjectHome : ${env.projectHomeDir}/angular-web-modules 

templateDir : ${env.codegenProjectHome}/templates

transformations :
   - template : java/api-method
     params :
       apiType : Post
       url : /Account
       returnType : Account
       requestBodyType : Account
       methodName : saveAccount
       message : Saving account data
