# This generates the skeleton for a Rest API definition. Outputs to console

env :
    projectHomeDir : /Users/sandeep/projects/source/CodeGenConfigs/
    codegenProjectHome : ${env.projectHomeDir}/angular-web-modules 

templateDir : ${env.codegenProjectHome}/templates

extHandlerDir : ${env.codegenProjectHome}/ext-handlers

transformations :
   - template : java/java-bean
     params :
       className : FixedDeposit
       attributes :
         - Integer id
         - Account baseAccount
         - Date openDate
         - Date matureDate
         - int openAmt
         - int matureAmt
         - boolean autoRenew
         - float interestRate
         - int recurringAmt
         - int recurringDom
         
         
