# This generates the skeleton for a Rest API definition. Outputs to console

env :
    projectHomeDir : /Users/sandeep/projects/source/CodeGenConfigs/
    codegenProjectHome : ${env.projectHomeDir}/angular-web-modules 

templateDir : ${env.codegenProjectHome}/templates

extHandlerDir : ${env.codegenProjectHome}/ext-handlers

transformations :
   - template : java/jpa-entity
     params :
       tableName : mf_txn
       className : MutualFundTxn
       attributes :
         - String ownerName
         - String scheme
         - String txnType
         - String txnChannel
         - Date txnDate
         - float navPerUnit
         - float numUnits
         - float amount
         
         
