# This code generator configuration creates a code snippet for adding
# a tile definition in /views/landing/landing.html file
env :
    baseDir : /home/sandeep/temp/codegen

templateDir : ${env.baseDir}/templates

# Mandatory attributes for each transformation
# - targetHTMLFile = The path of the HTML file relative to web root
# - tileName = The display name of the tile
transformations :
   - template : tile.st
     params :
        targetHTMLFile : /views/account/account.html
        tileName : Account
        