# A module is a single page application hosting directory and caters to
# functionalit surrounding a single functional module of the application.
#
# A boilerplate directory structure of a module looks like the following:
#
# /static/views/<moduleName>
#   +-- js
#   |    +-- controller.js
#   |    +-- directive.js
#   |    +-- route.js
#   |    +-- filter.js
#   |-- template
#   |    +-- prune-guard.txt
#   +-- <moduleName>.html
env :
    projectDisplayName : Capitalyst
    projectName : CapitalystServer
    moduleDirName : ledger
    moduleId : Ledger
    baseNgApp : capitalystNgApp
    projectHome : /Users/sandeep/projects/source/${env.projectName}
    viewsDir : ${env.projectHome}/src/main/resources/static/views
    moduleDirPath : ${env.viewsDir}/${env.moduleDirName}
    routeTemplateBasePath : /views/${env.moduleDirName}/template
    codegenProjectHome : /Users/sandeep/projects/source/CodeGenConfigs/angular-web-modules 

templateDir : ${env.codegenProjectHome}/templates

extHandlerDir : ${env.codegenProjectHome}/ext-handlers

mkdirsConfig :
    baseDirectory : ${env.moduleDirPath}
    directories :
        - js
        - template
    
transformations :
   - template : js/tile
     params :
        tileName : ${env.moduleId}
        targetHTMLFile : /views/${env.moduleDirName}/${env.moduleDirName}.html
        
   - template : js/controller
     destination : ${env.moduleDirPath}/js/controller.js
     params :
        title : ${env.moduleId}
        controllerName : ${env.moduleId}Controller
        
   - template : js/directive
     destination : ${env.moduleDirPath}/js/directive.js
        
   - template : js/route
     destination : ${env.moduleDirPath}/js/route.js
     extHandler : route-definitions-handler
     params :
        routeDefinitions :
           - routePath : /
             templateUrl : ${env.routeTemplateBasePath}/${env.moduleId}Home.html
             controllerName : ${env.moduleId}HomeController

   - template : js/filter
     destination : ${env.moduleDirPath}/js/filter.js

   - template : html/index-html
     destination : ${env.moduleDirPath}/${env.moduleDirName}.html
     params :
        pageTitle : ${env.moduleId}
        

        
        
        